### ISSUE TITLE
M7- Search Feature

### ISSUE THREAD

**Issue by jmeyers35** [jmeyers35/BuzzShelter#14]
Should support searching by gender, age range, and shelter name. Non-binary gender searching is extra credit! It seems like we _may_  have to restructure the information stored in Shelter to implement this in a meaningful way but we'll see.

**Comment by btdubs** [comment]
You got his Anthothy. We believe in you.

**Comment by btdubs** [comment]
Try the Android filter Class: https://developer.android.com/reference/android/widget/Filter.html
Here is a filter with recyclerview tutorial: https://www.androidhive.info/2017/11/android-recyclerview-with-search-filter-functionality/

Look up FuzzyWuzzy library for ideas towards fuzzy search terms.
