### ISSUE TITLE
M8-Vacancy Claiming

### ISSUE THREAD

**Issue by jmeyers35** [jmeyers35/BuzzShelter#17]
Add support for users to claim a number of vacancies at a shelter. They cannot claim vacancies at multiple shelters, and they obviously cannot claim more spots than a shelter has vacancies. DATA MUST PERSIST FOR THIS MILESTONE!

**Comment by btdubs** [comment]
When you login/register do it through firebase (implemented) and then pull data from users/<username>/... 

Shelter detail activity needs to have new button added that you can type in number and then submit to claim vacancies. Check that there are vacancies available or the user hasn't claimed too many. Alert him of failure by toast.
Update the shelter to have a totalcapacity and vacancy attributes. On reservation, update vacancy and store that to shelters/<shelterid>/vacancy

Use csv script to send data to firebase in the first place

**Comment by btdubs** [comment]
Needs to have a user that knows his # of vacancies claimed and at which shelter.
User needs to ask shelter to claim a vacancy. Handle success or failure.
The shelter needs to be able to check if the vacancies you want to claim are allowed (i.e. enough space, not trying to claim too many) and report back to user if it was allowed

In shelter detailed view, there needs to be some input of a number and some button for claiming vacancy. Here the user object will request vacancy claiming. Toast if success or failure.

In mainActivity, there needs to be a button the clear vacancies. This will take the current user object and tell him to clear his vacancies. The user object should have method that clears his shelter and number of vacancies claimed. Toast the user on success.
