### ISSUE TITLE
M9- Map

### ISSUE THREAD

**Issue by jmeyers35** [jmeyers35/BuzzShelter#18]
Implement a map display which can show the shelters and allow the user to filter the results. Reuse the functionality from the previous milestone. Clicking the pin should display details of the shelter. This would be a good time to implement location services(ie directions) as well.

**Comment by btdubs** [comment]
The details display of the shelter should just launching the same activity that is launched when the list item is clicked. Careful because it uses fragments and data needs to be sent with the intent. Take a look at the shelterlistactivity and it should make sense though.

**Comment by btdubs** [comment]
Info for using google maps api and adding marker.
https://developers.google.com/maps/documentation/android-api/map-with-marker

**Comment by btdubs** [comment]
Use the filter from the shelterlist activity (don't copy paste please) and the searchview in the toolbar like the shelterlist activity. The filter will hand you out a list of filteredMValues and that can be used to populate the map
